---
# ;)
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false
jaeger:
  enabled: false

opentelemetry-collector:
  config:
    processors:
      k8sattributes:
        passthrough: false
        filter:
          node_from_env_var: K8S_NODE_NAME
        pod_association:
          # Pod assocations are used to extract a pod ID from one or more sources.
          # These are used to match up telemetry.
          # Each has a maximum of 4 association sources.
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
              - from: resource_attribute
                name: k8s.node.name
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: connection
        extract:
          labels:
            - tag_name: service.name
              key: app.kubernetes.io/name
              from: pod
            - tag_name: service.name
              key: k8s-app
              from: pod
            - tag_name: k8s.app.instance
              key: app.kubernetes.io/instance
              from: pod
            - tag_name: service.version
              key: app.kubernetes.io/version
              from: pod
            - tag_name: k8s.app.component
              key: app.kubernetes.io/component
              from: pod
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.replicaset.uid
            - k8s.daemonset.name
            - k8s.daemonset.uid
            - k8s.job.name
            - k8s.job.uid
            - k8s.container.name
            - k8s.cronjob.name
            - k8s.statefulset.name
            - k8s.statefulset.uid
            - container.image.tag
            - container.image.name
            - k8s.cluster.uid
    exporters:
      debug:
        verbosity: normal
      otlp/cloudobs:
        endpoint: ingest.lightstep.com:443
        headers:
          lightstep-access-token: "YOUR_TOKEN"
    service:
      pipelines:
        metrics/collector-monitoring:
          receivers: [prometheus]
          processors: [k8sattributes, batch]
          exporters: [debug, otlp/cloudobs]
        metrics:
          receivers:
            - otlp
          processors:
            - batch
            - k8sattributes
          exporters:
            - debug
            - otlp/cloudobs
        traces:
          receivers:
            - otlp
          processors:
            - batch
            - k8sattributes
          exporters:
            - debug
            - otlp/cloudobs
        logs:
          receivers:
            - otlp
          processors:
            - batch
            - k8sattributes
          exporters:
            - debug
            - otlp/cloudobs
