---
# ;)
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false
jaeger:
  enabled: false

opentelemetry-collector:
  config:
    processors:
      k8sattributes:
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.deployment.uid
            - k8s.statefulset.name
            - k8s.statefulset.uid
            - k8s.daemonset.name
            - k8s.daemonset.uid
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.job.uid
            - k8s.node.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.container.name
            - container.image.tag
            - container.image.name
            - k8s.pod.start_time
            - k8s.cluster.uid
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
    exporters:
      debug:
        verbosity: normal
      otlp/cloudobs:
        endpoint: ingest.lightstep.com:443
        headers:
          lightstep-access-token: "YOUR_TOKEN"
    service:
      pipelines:
        metrics/collector-monitoring:
          receivers: [prometheus]
          processors: [k8sattributes, batch]
          exporters: [debug, otlp/cloudobs]
        metrics:
          receivers:
            - otlp
          processors:
            - batch
            - k8sattributes
          exporters:
            - debug
            - otlp/cloudobs
        traces:
          receivers:
            - otlp
          processors:
            - batch
            - k8sattributes
          exporters:
            - debug
            - otlp/cloudobs
        logs:
          receivers:
            - otlp
          processors:
            - batch
            - k8sattributes
          exporters:
            - debug
            - otlp/cloudobs
