receivers:
  hostmetrics:
    collection_interval: 10s
    # partial list of possible scraperss
    scrapers:
      cpu:
      memory:
      disk:
      load:
      network:
      processes:

processors:
  batch:
    timeout: 5s
  metricstransform/addhost:
    transforms:
      - include: (.*)
        match_type: regexp
        action: update
        new_name: ${env:HOSTNAME}.$${0}
  resourcedetection:
    detectors: [env,system]

exporters:
  prometheus:
    endpoint: "localhost:9090"
    # TODO: should this be used?
    # namespace: test-space
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, metricstransform/addhost, resourcedetection]
      exporters: [prometheus]

extensions:
  health_check:
  pprof:
