receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:
      paging:
      processes:

processors:
  batch:
    timeout: 5s
  resourcedetection:
    detectors: [env,system]

exporters:
  carbon:
    endpoint: "localhost:2003"  # The address of the Carbon/Graphite server
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, resourcedetection]
      exporters: [carbon]

extensions:
  health_check:
  pprof:
