# TODO: 
# - how to represent user-defined tags
apiVersion: v0.0.1
name: otel-to-servicenow-cis
description: Description of inferred resources and relationships from telemetry attributes
#
# Resources
# These get turned into CI Classes
#
resources:
# CloudObs service
- name: service
  ci: cmdb_ci_service_calculated
  sources:
    - metrics
    - logs
    - spans
  id_attributes:
    - service.name
  attributes:
    - service.id
    - service.namespace
    - service.version

# Server
- name: server
  ci: cmdb_ci_server
  sources:
    - metrics
    - logs
    - spans
  id_attributes:
    - host.name
  attributes:
    - host.id
    - os.type

# Kubernetes cluster
- name: k8s.cluster
  ci: cmdb_ci_kubernetes_cluster
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.namespace.phase
  metric_instrumentation: otelcol/k8sclusterreceiver
  id_attributes:
    - k8s.cluster.name
    - k8s.cluster.uid

# Kubernetes namespace
- name: k8s.namespace
  ci: cmdb_ci_kubernetes_namespace
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.namespace.phase
  metric_instrumentation: otelcol/k8sclusterreceiver
  id_attributes:
    - k8s.cluster.name
    - k8s.cluster.uid
    - k8s.namespace.name

# Kubernetes node
- name: k8s.node
  ci: cmdb_ci_kubernetes_node
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.node.cpu.time
  metric_instrumentation: otelcol/kubeletstatsreceiver
  id_attributes:
    - k8s.cluster.name
    - k8s.cluster.uid
    - k8s.node.name
  attributes:
    - k8s.node.uid

# Kubernetes deployment
- name: k8s.deployment
  ci: cmdb_ci_kubernetes_deployment
  sources:
    - metrics
    - spans
  metric_source: k8s.deployment.available
  metric_instrumentation: otelcol/k8sclusterreceiver
  id_attributes:
    - k8s.cluster.uid
    - k8s.cluster.name
    - k8s.namespace.name
    - k8s.deployment.name
    - k8s.deployment.uid

# Kubernetes replicaset
- name: k8s.replicaset
  ci: cmdb_ci_kubernetes_replicaset
  sources:
    - metrics
    - spans
  metric_source: k8s.replicaset.available
  metric_instrumentation: otelcol/k8sclusterreceiver
  id_attributes:
    - k8s.cluster.uid
    - k8s.cluster.name
    - k8s.namespace.name
    - k8s.replicaset.name
    - k8s.replicaset.uid

# Kubernetes replicaset
- name: k8s.daemonset
  ci: cmdb_ci_kubernetes_daemonset
  sources:
    - metrics
    - spans
  metric_source: k8s.daemonset.ready_nodes
  metric_instrumentation: otelcol/kubeletstatsreceiver
  id_attributes:
    - k8s.cluster.uid
    - k8s.cluster.name
    - k8s.namespace.name
    - k8s.daemonset.name
    - k8s.daemonset.uid

# Kubernetes pod
- name: k8s.pod
  ci: cmdb_ci_kubernetes_pod
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.pod.memory.usage
  metric_instrumentation: otelcol/kubeletstatsreceiver
  id_attributes:
    - k8s.cluster.name
    - k8s.cluster.uid
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.pod.uid

# Container
- name: container
  ci: cmdb_ci_docker_container
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.container.ready
  metric_instrumentation: otelcol/k8sclusterreceiver
  id_attributes:
    - container.id

# Container image
- name: container.image
  ci: cmdb_ci_docker_image
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.container.ready
  metric_instrumentation: otelcol/k8sclusterreceiver
  id_attributes:
    - container.id
    - container.image.name
    - container.image.tag

# Cloud service account
- name: cloud.account
  ci: cmdb_ci_cloud_service_account
  sources:
    - logs
    - spans
    - metrics
  id_attributes:
    - cloud.account.id
    - cloud.provider

# Cloud Data Center
- name: cloud.availability_zone
  ci: cmdb_ci_logical_datacenter
  sources:
    - logs
    - spans
    - metrics
  id_attributes:
    - cloud.region
    - cloud.provider
    - cloud.availability_zone

# AWS Resource
- name: cloud.aws.resource
  ci: multiple
  sources:
    - logs
    - spans
    - metrics
  id_attributes:
    - cloud.region
    - cloud.provider
    - cloud.availability_zone
    - cloud.resource_id
    - cloud.resource_name # TODO: is service.name better here?

# Azure Resource
# TODO: I think additional azure CIs are needed
- name: cloud.azure.resource
  ci: multiple
  sources:
    - logs
    - spans
    - metrics
  id_attributes:
    - cloud.region
    - cloud.provider
    - cloud.availability_zone
    - cloud.resource_id
  attributes:
    - cloud.resource_name

# Certificate
- name: certificate
  ci: cmdb_ci_certificate
  #conditions:
  #  - attributes["instrumentation.name"] == "otelcol/osqueryreciever"
  sources:
    - logs
  id_attributes:
    - sha1
  attributes:
    - issuer
    - subject
    - serial
#
# Relationships
# These get turned into CI relationships
# 
relationships:
# service -> service
- name: service.to.service
  ci_from: cmdb_ci_service_calculated
  ci_to: cmdb_ci_service_calculated
  sources:
    - metrics
  id_attributes:
    - service.name  
    - peer.service

- name: pod.to.image
  ci_from: cmdb_ci_kubernetes_pod
  ci_to: cmdb_ci_docker_image
  metric_source: k8s.container.ready
  metric_instrumentation: otelcol/k8sclusterreceiver
  sources:
    - metrics
  id_attributes:
    - k8s.cluster.uid
    - k8s.cluster.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.pod.uid
    - container.image.name
    - container.image.tag

# service -> service (following Grafana Tempo convention)
# https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/
- name: service.to.service.grafana.tempo
  ci_from: cmdb_ci_service_calculated
  ci_to: cmdb_ci_service_calculated
  metric_source: tempo_service_graph_request_total
  sources:
    - metrics
  id_attributes:
    - client
    - server

# deployment workload -> service
- name: deployment.to.service
  ci_from: cmdb_ci_kubernetes_deployment
  ci_to: cmdb_ci_service_calculated
  sources:
    - metrics
    - logs
    - spans
  metric_source: k8s.deployment.available
  id_attributes:
    - k8s.cluster.uid
    - k8s.cluster.name
    - k8s.namespace.name
    - k8s.deployment.name
    - k8s.deployment.uid
    - service.name