# Build is responsible for testing builds on all supported platforms.
# It is broken up into three separate jobs with targeted builds so that each OS will
# build in parallel and speed up overall CI time.
name: Build
on:
  pull_request:
    paths:
      - '!docs/**'
      - '!readme.md'

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.21.5'
          check-latest: true
      - name: Install builder
        working-directory: ./collector
        run: |
            go install go.opentelemetry.io/collector/cmd/builder@v0.95.0     
      - name: Build
        working-directory: ./collector
        run: make build-linux
      - name: Validate
        working-directory: ./collector
        run: make validate-linux
#   build_darwin:
#     runs-on: macos-14
#     steps:
#       - name: Checkout Sources
#         uses: actions/checkout@v4
#       - name: Setup Go
#         uses: actions/setup-go@v5
#         with:
#             go-version: '~1.21.5'
#             check-latest: true
#       - name: Install builder
#         working-directory: ./collector
#         run: |
#             go install go.opentelemetry.io/collector/cmd/builder@v0.95.0   
#       - name: Build
#         working-directory: ./collector
#         run: make build-darwin
#   build_windows:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout Sources
#         uses: actions/checkout@v4
#       - name: Setup Go
#         uses: actions/setup-go@v5
#         with:
#             go-version: '~1.21.5'
#             check-latest: true
#       - name: Install builder
#         working-directory: ./collector
#         run: |
#             go install go.opentelemetry.io/collector/cmd/builder@v0.95.0      
#       - name: Build
#         working-directory: ./collector
#         run: make build-windows
