name: Check Pull Request
on:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: collector/config/*.yaml collector/config-k8s/*.yaml
          config_file: .yamllint.yml
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: 'docs/'
          max-depth: 2
