# based on: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.github/workflows/release.yaml
name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    permissions:
      id-token: write
      packages: write
      contents: write

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,linux/arm/v7

      - uses: docker/setup-buildx-action@v3

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.21.5'
          check-latest: true

      - name: Generate distribution sources
        run: |
            go install go.opentelemetry.io/collector/cmd/builder@v0.95.0
            cd collector
            builder --config otelcol-builder.yaml --skip-compilation

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=sign --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
