# based on: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.github/workflows/release.yaml
name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    permissions:
      id-token: write
      packages: write
      contents: write

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,linux/arm/v7

      - uses: docker/setup-buildx-action@v3

      - uses: actions/setup-go@v5
        with:
          go-version: '~1.21.5'
          check-latest: true

      - name: Install tools
        working-directory: collector
        run: make install-tools

      - name: Generate distribution sources
        working-directory: collector
        run: builder --config otelcol-builder.yaml --skip-compilation

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: anchore/sbom-action/download-syft@v0.15.8

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.3'

      - name: Build cosign key file
        run: 'echo "$COSIGN_PRIVATE_KEY" >> cosign.key'
        shell: bash
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.ORG_COSIGN_PRIVATE_KEY}}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 2h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.ORG_COSIGN_PWD }}

  postrelease:
    runs-on: ubuntu-20.04
    needs: release
    steps:
      - name: Untar latest prerelease
        uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          extract: true
          preRelease: true
          fileName: otelcol-servicenow_*_linux_amd64.tar.gz 
      - name:  Validate otelcol-servicenow
        run: ./otelcol-servicenow validate --config config/otelcol-linux-hostmetrics.yaml
