name: Tests
on:
  pull_request:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-20.04, macos-14, windows-2022-8-cores]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - name: Run tests
        working-directory: ./collector
        run: |
          make test
            